name: 'testing'
on: [push]

env:
  TEST_VAR: "Testing"
  
jobs:
  test-job:
    name: 'Test Job'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
        
    steps:
    - name: Output env var
      env:
        TEST: ${{ env.TEST_VAR }}
      run: echo "Output is ${TEST}"
